/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GuideHiringAVideoEditorRouteImport } from './routes/guide.hiring-a-video-editor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideHiringAVideoEditorRoute = GuideHiringAVideoEditorRouteImport.update({
  id: '/guide/hiring-a-video-editor',
  path: '/guide/hiring-a-video-editor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guide/hiring-a-video-editor': typeof GuideHiringAVideoEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guide/hiring-a-video-editor': typeof GuideHiringAVideoEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guide/hiring-a-video-editor': typeof GuideHiringAVideoEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitemap.xml' | '/guide/hiring-a-video-editor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/guide/hiring-a-video-editor'
  id: '__root__' | '/' | '/sitemap.xml' | '/guide/hiring-a-video-editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GuideHiringAVideoEditorRoute: typeof GuideHiringAVideoEditorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/hiring-a-video-editor': {
      id: '/guide/hiring-a-video-editor'
      path: '/guide/hiring-a-video-editor'
      fullPath: '/guide/hiring-a-video-editor'
      preLoaderRoute: typeof GuideHiringAVideoEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GuideHiringAVideoEditorRoute: GuideHiringAVideoEditorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
